swarns={
  'manager' => {:ip =>'12',:name =>'manager', :box =>'ubuntu/trusty64'},
  'work1'  => {:ip =>'13',:name =>'work', :box =>'ubuntu/trusty64'},
  'work2'  => {:ip =>'14',:name =>'work', :box =>'ubuntu/trusty64'},
}
Vagrant.configure("2") do |config|

    
  swarns.each do |nome, conf|

    config.vm.define "#{nome}" do |server1|

        server1.vm.box = "ubuntu/focal64"
        server1.vm.box_check_update = false
        server1.vm.synced_folder "./file", "/file"
        server1.vm.synced_folder ".", "/vagrant", disabled:true

        if "#{nome}" == 'manager'  then
              server1.vm.network "forwarded_port", guest:9000, host:8999
              server1.vm.network "private_network", ip: "192.168.56.#{conf[:ip]}"
              server1.vm.hostname="#{nome}" 
              server1.vm.provision "shell", path: "file/manager.sh"
              server1.vm.provider "virtualbox" do |vb|
                vb.name = "#{nome}"
            
                # Display the VirtualBox GUI when booting the machine
                vb.gui = false
                # Customize the amount of memory on the VM:
                vb.memory = "1024"
                vb.cpus=1
              end
              
          else
              server1.vm.network "private_network", ip: "192.168.56.#{conf[:ip]}"
              server1.vm.hostname="#{nome}" 
              server1.vm.provision "shell", path: "file/works.sh"
              server1.vm.provider "virtualbox" do |vb|
                  vb.name = "#{nome}" 
                  # Display the VirtualBox GUI when booting the machine
                  vb.gui = false
                  # Customize the amount of memory on the VM:
                  vb.memory = "2048"
                  vb.cpus=2
              
              end
        
        
        end 

    end 
    

  end  
  
  
end
