apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverdb
  labels:
    app: sevbancodb
spec:
  selector:
    matchLabels:
      app: sevbancodb
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sevbancodb
    spec:
      containers:
      - name: mybando
        imagePullPolicy: IfNotPresent        
        image: localhost:5001/mysqldb:1.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
         - containerPort: 3306