---
- name: configurar servidor DB.
  hosts: db01

  user: vagrant
  become: yes
  vars_files:
    - vars/main.yaml

  vars:
    - dbname: "db01"
    - dbusername: "root"
    - dbpassword: "123456"

  roles:
   - configurar-default-so
   - role: geerlingguy.mysql
