
Vagrant.configure("2") do |config|
 
  config.vm.box = "centos/7"
  config.vm.hostname = "control-node"
  #config.vm.network "public_network", bridge: "wlp2s0", ip: "192.168.1.22"
  #config.vm.network "public_network", ip: "192.168.1.12", hostname: true

  config.vm.network "private_network", ip: "192.168.56.10", netmask: "255.255.255.0"

  config.vm.provision "shell", path: "provision.sh"
  config.vm.synced_folder ".", "/vagrant", type:"nfs"

end
