Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  
  config.vm.define "server1" do |server1| 
      server1.vm.hostname="srv01" 
      server1.vm.network "private_network", ip: "192.168.56.12"
      server1.vm.synced_folder "./file", "/file",type: "rsync"
      server1.vm.synced_folder ".", "/vagrant", disabled:true

      config.vm.provider "virtualbox" do |vb|
        vb.name="srv01" 
        # Display the VirtualBox GUI when booting the machine
        vb.gui = false
        # Customize the amount of memory on the VM:
        vb.memory = "1024"
        vb.cpus=1

      end
  end

  config.vm.define "server2" do |server2| 
    server2.vm.hostname="srv02" 
    server2.vm.network "private_network", ip: "192.168.56.13"
    server2.vm.synced_folder "./file", "/file",type: "rsync"
    server2.vm.synced_folder ".", "/vagrant", disabled:true

    config.vm.provider "virtualbox" do |vb|
      vb.name="srv02" 
      # Display the VirtualBox GUI when booting the machine
      vb.gui = false
      # Customize the amount of memory on the VM:
      vb.memory = "1024"
      vb.cpus=1

    end

    config.vm.define "server3" do |server3| 
      server3.vm.hostname="srv03" 
      server3.vm.network "private_network", ip: "192.168.56.14"
      server3.vm.synced_folder "./file", "/file",type: "rsync"
      server3.vm.synced_folder ".", "/vagrant", disabled:true
  
      config.vm.provider "virtualbox" do |vb|
        vb.name="srv03" 
        # Display the VirtualBox GUI when booting the machine
        vb.gui = false
        # Customize the amount of memory on the VM:
        vb.memory = "1024"
        vb.cpus=1
  
      end

end

end
