Vagrant.configure("2") do |config|

  config.vm.box = "chenhan/ubuntu-desktop-20.04"
  config.vm.box_check_update = false

  config.vm.define "server1" do |server1| 
      server1.vm.hostname="srv01" 
      
      (0..0).each do |i|
        server1.vm.disk :disk, name: "disk-#{i}", size: "20GB"
      end
      server1.vm.network "private_network", ip: "192.168.56.12"
      server1.vm.network "forwarded_port", guest:8080, host:8089 
 
      server1.vm.synced_folder ".", "/vagrant", disabled:true
     
      server1.vm.provider "virtualbox" do |vb|
        vb.name = "srv01" 
        # Display the VirtualBox GUI when booting the machine
        vb.gui = true
        # Customize the amount of memory on the VM:
        vb.memory = "8056"
        vb.cpus=4

      end
  end
end
