
Vagrant.configure("2") do |config|
 
  config.vm.box = "centos/7"
  config.vm.hostname = "db01"
  #config.vm.network "public_network", bridge: "wlp2s0", ip: "192.168.1.22"
  #config.vm.network "public_network", ip: "192.168.1.12", hostname: true

  config.vm.network "private_network", ip: "192.168.56.12", netmask: "255.255.255.0"
  config.vm.network "forwarded_port", guest: 3306,  host:3306
 
  config.vm.provision "shell", path: "provision.sh"

end
